# Generated by Django 4.1.6 on 2023-02-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ville',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
